version: 2
jobs:
  build:
    docker:     
      - image: ubuntu:latest

    working_directory: ~/repo

    steps:
      - checkout
      # run something after the dotscience task
      - run:
          name: Post run task
          environment:
            FOO: BAR
          command: |
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_SHA1}